import json

ss_path = r"E:\comfyUi_latest\ComfyUI_windows_portable\ComfyUI\user\default\workflows\jaisal_single_shot.json"
d = json.load(open(ss_path))

# 15-part per-second timeline (the timeline technique). Sequence:
# walk -> look both sides -> throw plane -> plane drifts -> wait (wind) -> jump ->
# plane floats + lands on water. Title composited in post (NOT on the plane).
# Background lock (pure white, no wooden/mica) repeated in EVERY second.
TITLE_PROMPT = (
    "MANDATORY SHOT CONSTRAINT, HIGHEST PRIORITY ABOVE ALL ELSE: this is a 2D vector "
    "line-art animation. ONE continuous take. Every frame is a MEDIUM shot (the "
    "figure's full body visible, a little of the bridge and river around him). NO "
    "wide shots, NO extreme close-ups. The camera is a STATIC EYE-LEVEL MEDIUM shot "
    "for the whole take - it is LOCKED and does NOT move, does NOT push in, does NOT "
    "drift, does NOT tilt, does NOT pan, does NOT zoom, does NOT orbit. REJECT any "
    "camera angle that is not a static eye-level MEDIUM shot.\n\n"
    "BACKGROUND LOCK, HIGHEST PRIORITY, APPLIES TO EVERY SECOND: the background is "
    "PURE WHITE (a clean empty white void), EXACTLY like the reference image. NOT "
    "cream, NOT beige, NOT tan, NOT paper, NOT wooden, NOT mica. NO wooden overlay, "
    "NO wooden floor, NO wooden table, NO wood grain, NO mica, NO brown tones, NO "
    "warm tones, NO table, NO room, NO wall, NO scene, NO environment, NO setting, "
    "NO color, NO shading, NO additional background elements, NO out-of-space "
    "objects. The background is a flat pure white void with ONLY black ink lines on "
    "it, the whole time. This background lock is repeated in every second of the "
    "timeline below.\n\n"
    "subject_definitions:\n"
    "<Subject 1> is a simple 2D vector line-art stick figure schoolboy - a round "
    "head, a line body, line arms, line legs, clean confident line work, a small "
    "line-art school bag on his back. ONLY ONE character, no other people, no "
    "duplicates.\n"
    "<Subject 2> is a simple line-art stone bridge with a LOW HANDRAIL (a "
    "horizontal line with small vertical post lines) crossing a river drawn as "
    "scattered small dots and short wavy dashes. The bridge is HIGH above the river "
    "- a clear visible gap between the deck and the water below.\n"
    "<Subject 3> is a small line-art paper plane (a simple folded triangle of "
    "lines).\n\n"
    "summary:\n"
    "[reference generation] A simple 2D vector line-art animation in a clean "
    "confident line-work style. A stick figure schoolboy walks slowly on a line-art "
    "bridge, stops and looks around to both sides, throws a paper plane into the "
    "river, waits a moment while the paper plane drifts slowly and the wind blows, "
    "then jumps into the river. The paper plane slowly floats and lands on the "
    "water. Simple, funny, no special effects. Every frame is a MEDIUM shot (the "
    "figure's full body visible). All transitions are smooth and organic.\n\n"
    "retention_analysis:\n"
    "<Subject 1> (appears in 0.00-10.00 seconds): fully_preserved - the stick "
    "figure's round head, line body, line arms, line legs, line-art school bag, and "
    "clean line work are retained. There is ONLY ONE character - never two, never a "
    "duplicate.\n"
    "<Subject 2> (appears in 0.00-10.00 seconds): fully_preserved - the line-art "
    "bridge with low handrail, the high deck above the water, and the wavy line "
    "river water are retained.\n"
    "<Subject 3> (appears in 3.00-15.00 seconds): fully_preserved - the line-art "
    "paper plane is retained.\n"
    "The STYLE stays EXACTLY consistent across all seconds - the same 2D vector "
    "line-art look, the same clean line work, the same PURE WHITE background - so no "
    "second looks like a different scene.\n\n"
    "GLOBAL CAMERA LOCK (HIGHEST PRIORITY, APPLIES TO EVERY SECOND 0.00-15.00):\n"
    "A STATIC EYE-LEVEL MEDIUM shot for the entire take. The camera is LOCKED - it "
    "does NOT move, does NOT push in, does NOT drift, does NOT tilt, does NOT pan, "
    "does NOT zoom, does NOT orbit. DEEP FOCUS throughout (every line in the frame "
    "is sharp). NO wide shots, NO extreme close-ups. The figure is NEVER "
    "duplicated, NEVER a second figure, NEVER a crowd. The background is PURE WHITE "
    "the whole time - NO wooden overlay, NO mica, NO color, NO scene clutter.\n\n"
    "detailed_description:\n"
    "The target video is a 15-second 2D vector line-art animation in a clean "
    "confident line-work style, a simple stick figure character, flat 2D, minimal, "
    "simple, no shading, no 3d, no photorealistic, no cartoon shading, just lines. "
    "Every frame is a MEDIUM shot (the figure's full body visible, a little of the "
    "bridge and river around him). NO wide shots, NO extreme close-ups. DEEP FOCUS "
    "throughout (every line in the frame is sharp). The background is PURE WHITE "
    "the whole time - black ink lines on a clean white void ONLY, NO wooden "
    "overlay, NO mica, NO color, NO scene clutter. The camera is a STATIC EYE-LEVEL "
    "MEDIUM shot, locked, the whole time.\n\n"
    "The sequence is split into 15 per-second parts. Each part names the figure's "
    "exact state and the one action happening in that second. The background is "
    "pure white in every part.\n\n"
    "0.00-1.00 second: the figure walks SLOWLY along the line-art bridge, his line "
    "legs in a slow walking stride, his line arms swinging gently. He is ON the "
    "bridge. The background is pure white, black ink lines only.\n"
    "1.00-2.00 second: the figure STOPS walking and TURNS HIS HEAD to look to one "
    "side (his left). He is still ON the bridge. The background is pure white, "
    "black ink lines only.\n"
    "2.00-3.00 second: the figure TURNS HIS HEAD to look to the other side (his "
    "right), looking around both ways. He is still ON the bridge. The background is "
    "pure white, black ink lines only.\n"
    "3.00-4.00 second: the figure THROWS a small line-art paper plane <Subject 3> "
    "into the river below - one line arm extended forward, the paper plane flying "
    "away from his hand toward the water. He is still ON the bridge. The background "
    "is pure white, black ink lines only.\n"
    "4.00-5.00 second: the paper plane <Subject 3> drifts slowly toward one side of "
    "the river, floating on the water. The figure watches it. He is still ON the "
    "bridge. The background is pure white, black ink lines only.\n"
    "5.00-6.00 second: the figure WAITS a moment, standing still on the bridge, "
    "watching the paper plane. The paper plane is still moving slowly, drifting. "
    "The wind is blowing (a few line-art wind lines). He is still ON the bridge. "
    "The background is pure white, black ink lines only.\n"
    "6.00-7.00 second: the figure continues to WAIT, the paper plane drifts "
    "slowly, the wind blows. He is still ON the bridge. The background is pure "
    "white, black ink lines only.\n"
    "7.00-8.00 second: the figure CROUCHES and prepares to jump, his line legs "
    "bent, his line arms out. He is still ON the bridge. The background is pure "
    "white, black ink lines only.\n"
    "8.00-9.00 second: the figure JUMPS off the edge of the high bridge into the "
    "river below. He LEAVES the bridge - he is NO LONGER on the bridge, he is in "
    "the AIR, his line body in a mid-air jumping pose, his line arms out, his line "
    "legs bent, a real drop from the high deck into the water. The background is "
    "pure white, black ink lines only.\n"
    "9.00-10.00 second: the figure is in the AIR, falling into the water, his line "
    "body in a mid-air jumping pose. The background is pure white, black ink lines "
    "only.\n"
    "10.00-11.00 second: the figure LANDS in the water with a soft splash (a few "
    "line-art splash lines). He is in the water, not on the bridge. The background "
    "is pure white, black ink lines only.\n"
    "11.00-12.00 second: the paper plane <Subject 3> slowly floats on the water "
    "surface, drifting gently. The figure is in the water (not visible). The "
    "background is pure white, black ink lines only.\n"
    "12.00-13.00 second: the paper plane <Subject 3> slowly drifts and LANDS on "
    "the water surface, floating calmly. The background is pure white, black ink "
    "lines only.\n"
    "13.00-14.00 second: calm water, the paper plane <Subject 3> floats gently on "
    "the surface. The background is pure white, black ink lines only.\n"
    "14.00-15.00 second: a final calm still frame - the paper plane <Subject 3> "
    "floats on the calm water, a few line-art water dots and dashes. The background "
    "is pure white, black ink lines only.\n\n"
    "WHAT THE FIGURE DOES NOT DO: does NOT drink, does NOT hold a cup, does NOT "
    "hold a bottle, does NOT hold any object to his mouth, does NOT run, does NOT "
    "slide, is NOT duplicated, is NOT a second figure, is NOT a crowd. The figure "
    "does NOT jump before the paper plane has drifted (he waits first). The paper "
    "plane does NOT come back toward the figure, does NOT fly back, does NOT fill "
    "the screen. The figure does NOT walk on the bridge after jumping, does NOT "
    "return to the bridge, does NOT reappear on the bridge.\n\n"
    "overall_soundscape:\n"
    "Simple, quiet. A few soft footsteps on the bridge as the figure walks, a soft "
    "whoosh as the paper plane is thrown, a gentle wind as the paper plane drifts, "
    "a soft splash as the figure jumps into the river, then a calm quiet hush as "
    "the paper plane floats on the water. No music, no dialogue.\n\n"
    "non_diegetic_music:\n"
    "Only natural sounds, no musical instruments. No dialogue, no subtitles. The "
    "title 'The Jaisal Cut' is composited in post and is NOT rendered by the model."
)

for n in d["nodes"]:
    if n["id"] == 105:
        n["widgets_values"][0] = TITLE_PROMPT
        if "widgets_values_named" in n:
            n["widgets_values_named"]["prompt"] = TITLE_PROMPT
        print("node 105 (instance) prompt set")

for s in d.get("definitions", {}).get("subgraphs", []):
    for n in s.get("nodes", []):
        if n["id"] == 104:
            n["widgets_values"][0] = TITLE_PROMPT
            if "widgets_values_named" in n:
                n["widgets_values_named"]["prompt"] = TITLE_PROMPT
            print("internal node 104 prompt set")

json.dump(d, open(ss_path, "w"), indent=1)
print("done")
